name: deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.0'
      - name: Build Web-app
        run: |
          yarn ci
          yarn run build
      - name: deploy to prod
        uses: peaceiris/actions.gh.pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build